/**
 * PM2 Ecosystem Config Generator
 *
 * Generates a PM2 ecosystem.config.js for the Kora daemon process.
 * PM2 provides:
 * - Auto-restart on crash (max 10 restarts, exponential backoff)
 * - Log management (rotated daemon logs)
 * - Process monitoring (CPU/memory)
 * - Graceful shutdown via SIGTERM
 *
 * Usage:
 *   kora start --pm2          # Start with PM2 process management
 *   pm2 start ecosystem.config.js
 *   pm2 status kora-daemon
 *   pm2 logs kora-daemon
 *   pm2 restart kora-daemon
 */

import path from "path";
import fs from "fs/promises";
import { logger } from "./logger.js";

export interface PM2EcosystemConfig {
  apps: Array<{
    name: string;
    script: string;
    args: string;
    cwd: string;
    interpreter: string;
    max_restarts: number;
    restart_delay: number;
    exp_backoff_restart_delay: number;
    max_memory_restart: string;
    env: Record<string, string>;
    error_file: string;
    out_file: string;
    merge_logs: boolean;
    log_date_format: string;
    kill_timeout: number;
    listen_timeout: number;
    autorestart: boolean;
  }>;
}

/**
 * Generate PM2 ecosystem config for the Kora daemon.
 */
export function generatePM2Config(opts: {
  isDev: boolean;
  port: number;
  globalConfigDir: string;
  daemonScript: string;
  backend?: string;
}): PM2EcosystemConfig {
  const appName = opts.isDev ? "kora-daemon-dev" : "kora-daemon";
  const args = ["start"];
  if (opts.isDev) args.push("--dev");
  if (opts.backend) args.push("--backend", opts.backend);
  args.push("--port", String(opts.port));

  return {
    apps: [
      {
        name: appName,
        script: opts.daemonScript,
        args: args.join(" "),
        cwd: process.cwd(),
        interpreter: "node",
        max_restarts: 10,
        restart_delay: 1000,
        exp_backoff_restart_delay: 1000, // Exponential backoff: 1s, 2s, 4s, 8s...
        max_memory_restart: "512M",
        env: {
          NODE_ENV: opts.isDev ? "development" : "production",
          KORA_DEV: opts.isDev ? "1" : "0",
          KORA_CONFIG_DIR: opts.globalConfigDir,
        },
        error_file: path.join(opts.globalConfigDir, "pm2-error.log"),
        out_file: path.join(opts.globalConfigDir, "pm2-out.log"),
        merge_logs: true,
        log_date_format: "YYYY-MM-DD HH:mm:ss",
        kill_timeout: 10000,   // 10s grace period for shutdown
        listen_timeout: 15000, // 15s to wait for app to be ready
        autorestart: true,
      },
    ],
  };
}

/**
 * Write PM2 ecosystem config to disk.
 */
export async function writePM2Config(
  globalConfigDir: string,
  config: PM2EcosystemConfig,
): Promise<string> {
  await fs.mkdir(globalConfigDir, { recursive: true });
  const configPath = path.join(globalConfigDir, "ecosystem.config.cjs");
  const content = `// Auto-generated by Kora — do not edit manually
// Usage: pm2 start ${configPath}
module.exports = ${JSON.stringify(config, null, 2)};
`;
  await fs.writeFile(configPath, content, "utf-8");
  logger.info(`[pm2] Wrote ecosystem config to ${configPath}`);
  return configPath;
}
